### ISSUE TITLE
Missing file info in CanonicalizeRequest

### ISSUE THREAD

**Issue by bep** [sass/embedded-protocol#40]
I'm in the process of implementing this in Go (for Hugo), and it's mostly smooth sailing, but I have stumbled upon a blocker. This may be me not understanding the spec, but I have studied it carefully.

Ref. this:

>When loading a URL, the host must first try resolving that URL relative to the canonical URL of the current file

What I then get to resolve a given import is something like this:

```go
&embeddedsass.OutboundMessage_CanonicalizeRequest{
  Id: 0,
  CompilationId: 0,
  ImporterId: 5679,
  Url: "colors",
}
```

I don't see how I can determine "the current file" from the above.

**Comment by johnfairh** [comment]
I reckon there are a couple of host/compiler typos in that paragraph: it's describing for context how the compiler implements `@import`, I think it should read:

> When loading a URL, the ~~host~~ **compiler** must first try resolving that URL relative to the canonical URL of the current file, and canonicalizing the result using the importer that loaded the current file. If this returns `null`, the ~~host~~ **compiler** must then try canonicalizing the original URL with each importer in order until one returns something other than `null`. That is the result of the import.

All we need in the host is the `Url` part -- same as the `Sass_Importer_Fn` `url` param if you're porting from libsass, except that one call is now split into two RPCs canonicalize + import.

**Comment by bep** [comment]
Thanks, after some investigation I notice that the URL is actually available in the `ImportRequest`.

**Comment by bep** [comment]
>All we need in the host is the Url part -- same as the Sass_Importer_Fn url 

`Sass_Importer_Fn` has both a `url` and a `prev`.

My concrete question would then be: where do I obtain the value of `prev`?

**Comment by johnfairh** [comment]
There's no equivalent of `sass_compiler_get_last_import()` which it looks like Go uses to generate `prev`.  I was wrong to say this was the 'same' as the libsass importer API: as the protocol doc says, the URL to canonicalize can be relative or absolute (including the path, which I think is closest to what you want).

If you explain what your importer has to do then someone (probably wiser than me) can explain how to port it (my libsass implementation was interrupted by its deprecation...)

**Comment by bep** [comment]
I'm trying to resolve the import relative to the file it's imported in. Which is, if I understand the spec, basically what the default import resolver does -- but I resolve against a virtual union file system.

So, given a file with this import:

```scss
@import "colors"
```

I need to need which file (or `stdint`) that has the import (e.g. `prev`).

**Comment by nex3** [comment]
The way the protocol handles relative imports is somewhat different than the way LibSass has historically done so (but more in line with how Ruby Sass did originally and Dart Sass does now). Rather than passing the previous import URL to the host and relying on the host to handle relative resolution in some custom way, the compiler relies on URLs' native notion of "relative resolution" handle relative imports consistently across all importers.

To begin with, every Sass stylesheet loaded by `@import`, `@use`, etc has a "canonical URL", an absolute URL that uniquely identifies that stylesheet. Stylesheets loaded from the filesystem are effectively loaded using a built-in importer that canonicalizes to `file:` URLs and loads those URLs from the physical filesystem.

To resolve an `@import`/`@use`/etc that appears within a given stylesheet, the compiler first resolves it relative to that stylesheet's canonical URL and checks whether the importer that loaded that stylesheet can load the new URL. If not, the compiler passes it to the full chain of importers and load paths to try to canonicalize it. If none of them can, the compiler throws an error.

For example, let's say you tell the compiler to compile the file `input.scss` with contents `@use "colors"`. Here's what happens:

* The compiler canonicalizes the file using the built-in filesystem importer (that's what happens if you specify a `path` input). This importer converts `input.scss` to the canonical URL `file:///path/to/working/directory/input.scss`, then loads that URL from disk and returns the file's contents.

* The compiler then sees `@use "colors"`. It first checks if `colors` can be resolved relative to `input.scss`. The resolved URL is `file:///path/to/working/directory/colors` (by standard URL resolution), so it checks whether that can be canonicalized by the filesystem importer (because that's the importer that loaded `input.scss`). If so, the canonical URL is sent back as an `ImportRequest` and that's how the URL is loaded.

* If the filesystem importer *can't* canonicalize `file:///path/to/working/directory/colors` (probably because no stylesheet exists with that name), the original unresolved URL `colors` is passed on to any other importers that are registered. These importers don't have access to the original stylesheet's URL because the way a URL is loaded shouldn't be sensitive to the context in which it appears, except for the specific case of relative URL resolution which is well-understood and consistent.

For your use-case you can:

* Use a `CompileRequest` with `input.string.importer.importer_id` set to your importer's ID and `input.string.url` set to the absolute `file:` URL of the entrypoint stylesheet. Doing this rather than using `input.path` will tell the compiler to use your custom importer rather than the default filesystem importer, so your importer will be called to handle relative URLs.

* When you receive a `CanonicalizeRequest` with an absolute URL, slice off the union FS root of the `url` and check the relative result against all the roots, then return whichever one has a file that matches.

* When you receive an `ImportRequest`, just load that file from the filesystem.

You could also use a `file_importer_id` to avoid the extra round-trip of the `ImportRequest`, once embedded Dart Sass has implemented that.

---

> I reckon there are a couple of host/compiler typos in that paragraph: it's describing for context how the compiler implements `@import`, I think it should read:
> 
> > When loading a URL, the ~host~ **compiler** must first try resolving that URL relative to the canonical URL of the current file, and canonicalizing the result using the importer that loaded the current file. If this returns `null`, the ~host~ **compiler** must then try canonicalizing the original URL with each importer in order until one returns something other than `null`. That is the result of the import.
> 
> All we need in the host is the `Url` part -- same as the `Sass_Importer_Fn` `url` param if you're porting from libsass, except that one call is now split into two RPCs canonicalize + import.

@johnfairh Good catch here—I've put out #41 to fix it.

**Comment by bep** [comment]
>Use a CompileRequest with input.string.importer.importer_id set to your importer's ID and input.string.url set to the absolute file: URL of the entrypoint stylesheet. Doing this rather than using input.path will tell the compiler to use your custom importer rather than the default filesystem importer, so your importer will be called to handle relative URLs.

What about transitive imports?

**Comment by bep** [comment]
Never mind, I think I see how this could work now. Thanks.
