### ISSUE TITLE
Recommendations for testing host implementations

### ISSUE THREAD

**Issue by stof** [sass/embedded-protocol#54]
Is there a recommended way for hosts to validate their implementation ?

I could imagine that hosts could implement a basic CLI wrapper compatible with the sass-spec runner and running sass-spec with `--impl dart-sass -c ./my-host-cli`. But that would probably not cover all features of the protocol (custom importers and host-provided functions for instance). So this might not be sufficient.

**Comment by nex3** [comment]
I think it's up to each host to write their own test suite that exercises the details of the API. This isn't something that's easy to share across hosts, because the point of a host is to adapt the protobuf API into something that feels native for its language—that's inherently going to be different from language to language. You can check out https://github.com/sass/embedded-host-node's test suite for some examples of how we're structuring it (although that may also eventually be merged into a shared JS API test suite, since there are going to be multiple implementations of the same API).
