### ISSUE TITLE
Add included sources to the CompileSuccess message

### ISSUE THREAD

**Issue by irundaia** [sass/embedded-protocol#62]
I'm working with an integration of the embedded sass compiler into a web framework.
This framework supports incremental compilation of assets. To be able to correctly trigger a new compilation, in case a included file has been imported, I'd need to tell the framework which files have been imported, such that the framework will also start monitoring those files.
To that end, I propose to add a `includedFiles` property to the `CompileSuccess` message.

Would this be something you would consider accepting a PR for?

P.s.
I know that this data is available in the compile result generated by dart-sass. Is there some other implementation I should consider?

**Comment by nex3** [comment]
This is probably something we can do, although it'll require also figuring out how to expose this information in the Dart API which we use to implement the compiler. Note that we'd need to expose this as `includedUrls`, not `includedFiles`, since the compiler only thinks about stylesheets in terms of their canonical URLs.

In https://github.com/sass/embedded-host-node/issues/47#issuecomment-840262296, @splaktar mentioned that the Angular team also wants access to this information, but I haven't gotten a clear answer on why. I'd like to understand all use-cases before designing the protocol.

**Comment by alan-agius4** [comment]
`includedFiles` are needed so that we/webpacks can build a full dependency graph for the compilation, so that when one of the dependencies changes it re-triggers a re-compilation.

https://github.com/webpack-contrib/sass-loader/blob/8b1ff66fd96d6a8872c40d02a4476942d08ea37f/src/index.js#L74

I think you meant `includePaths` and not `includeUrl`, a lot of downstream users depend on these and therefore without this option it would be hard to replace dart-sass without significant changes.

We’d also need addition APIs that sass-loader needs such as `importer` and `outputStyle`.
